"""Trusted finite source inventory; byte pins are not authentication."""

VENDOR_FILES = ({'commit': 'd15c666dfccff17f7350fe97d2fc7b71cb2cbaee',
  'git_blob_sha1': '57bc88a15a0ee8266c259b2667e64608d3f7e292',
  'path': 'vendor/semantic-abi/LICENSE',
  'repository': 'https://github.com/trustless-ai/semantic-abi.git',
  'sha256': 'c95bae1d1ce0235ecccd3560b772ec1efb97f348a79f0fbe0a634f0c2ccefe2c',
  'size_bytes': 11358,
  'source_path': 'LICENSE'},
 {'commit': 'd15c666dfccff17f7350fe97d2fc7b71cb2cbaee',
  'git_blob_sha1': '6ca207ef004cb69d03041e7e5c288a2be4968045',
  'path': 'vendor/semantic-abi/schema/LICENSE-CC0.txt',
  'repository': 'https://github.com/trustless-ai/semantic-abi.git',
  'sha256': '7179683e8000e6bdc9bbc60d85edf0a4ac8e76f951857f54fcb775d5886f1309',
  'size_bytes': 7049,
  'source_path': 'schema/LICENSE-CC0.txt'},
 {'commit': 'd15c666dfccff17f7350fe97d2fc7b71cb2cbaee',
  'git_blob_sha1': 'c292a23ef0f3c283e600522f7a13a42fdceee1d8',
  'path': 'vendor/semantic-abi/runner/src/linker.mjs',
  'repository': 'https://github.com/trustless-ai/semantic-abi.git',
  'sha256': 'bae8e519361989bfadbb5d226cb9940255cd954c60b40ba42136a2b11161d391',
  'size_bytes': 4044,
  'source_path': 'runner/src/linker.mjs'},
 {'commit': 'd15c666dfccff17f7350fe97d2fc7b71cb2cbaee',
  'git_blob_sha1': '647fc36d7d34756119a757d10b94b4473db44aa0',
  'path': 'vendor/semantic-abi/schema/manifest.schema.json',
  'repository': 'https://github.com/trustless-ai/semantic-abi.git',
  'sha256': '3219f51c7929ff915b71e5931a5d10edc5e15e73809fc2c47107592490bbe397',
  'size_bytes': 3842,
  'source_path': 'schema/manifest.schema.json'})

RVR_VENDOR_FILES = ({'commit': '549a7e150ddc75df88dc90ee93f331fea7464567',
  'git_blob_sha1': '9b85a39db99de06afeaf7ccae22a25fb2ac8f19f',
  'path': 'vendor/rvr-v0/LICENSE',
  'repository': 'https://github.com/pipavlo82/recomputable-verification-receipts.git',
  'sha256': 'fa7fe2e14249d2da31c0d2a0bbefc17a1994a93b42ae652a3dab450b6f1c0251',
  'size_bytes': 10377,
  'source_path': 'LICENSE'},
 {'commit': '549a7e150ddc75df88dc90ee93f331fea7464567',
  'git_blob_sha1': 'b0dfb0d389cbd6b634fef1c965a1b4077bca326e',
  'path': 'vendor/rvr-v0/adapter.py',
  'repository': 'https://github.com/pipavlo82/recomputable-verification-receipts.git',
  'sha256': '03505efc8ee993f118fad2c71f706870d25de0da61a393a1f18f7b310bded235',
  'size_bytes': 50109,
  'source_path': 'conformance/rvr-v0/adapter.py'},
 {'commit': '549a7e150ddc75df88dc90ee93f331fea7464567',
  'git_blob_sha1': '1525538d1c0316c2c5fc2e0ff2c7e8b4731d3169',
  'path': 'vendor/rvr-v0/verification-profile-manifest.schema.json',
  'repository': 'https://github.com/pipavlo82/recomputable-verification-receipts.git',
  'sha256': '148afeb484d3866c1caae82e574182c1b748dd461dfaeb1d8095ecf4905690c1',
  'size_bytes': 6479,
  'source_path': 'conformance/rvr-v0/verification-profile-manifest.schema.json'})

ALL_VENDOR_FILES = VENDOR_FILES + RVR_VENDOR_FILES

LOCAL_FILES = ('.gitattributes',
 '.github/workflows/ci.yml',
 '.gitignore',
 'docs/CONTRACT.md',
 'docs/INTEGRATION_MAP.md',
 'docs/NEXT_NATIVE_RVR.md',
 'docs/PROVENANCE.md',
 'docs/reference-pins.json',
 'docs/RVR_QEV_PROFILE_V0.md',
 'fixtures/corpus/backend-swap.package.json',
 'fixtures/corpus/backend-swap.request.json',
 'fixtures/corpus/bit-permutation.package.json',
 'fixtures/corpus/bit-permutation.request.json',
 'fixtures/corpus/boolean-count.package.json',
 'fixtures/corpus/boolean-count.request.json',
 'fixtures/corpus/codec.package.json',
 'fixtures/corpus/codec.request.json',
 'fixtures/corpus/counts-corrupt.package.json',
 'fixtures/corpus/counts-corrupt.request.json',
 'fixtures/corpus/duplicate-key.package.json',
 'fixtures/corpus/duplicate-key.request.json',
 'fixtures/corpus/elevate-authentic_qpu_execution.package.json',
 'fixtures/corpus/elevate-authentic_qpu_execution.request.json',
 'fixtures/corpus/elevate-cryptographic_rng.package.json',
 'fixtures/corpus/elevate-cryptographic_rng.request.json',
 'fixtures/corpus/elevate-device_certification.package.json',
 'fixtures/corpus/elevate-device_certification.request.json',
 'fixtures/corpus/elevate-distribution_equality.package.json',
 'fixtures/corpus/elevate-distribution_equality.request.json',
 'fixtures/corpus/elevate-min_entropy.package.json',
 'fixtures/corpus/elevate-min_entropy.request.json',
 'fixtures/corpus/elevate-sampler_independence.package.json',
 'fixtures/corpus/elevate-sampler_independence.request.json',
 'fixtures/corpus/endianness.package.json',
 'fixtures/corpus/endianness.request.json',
 'fixtures/corpus/expected-injection.package.json',
 'fixtures/corpus/expected-injection.request.json',
 'fixtures/corpus/expression.package.json',
 'fixtures/corpus/expression.request.json',
 'fixtures/corpus/float-count.package.json',
 'fixtures/corpus/float-count.request.json',
 'fixtures/corpus/job-swap.package.json',
 'fixtures/corpus/job-swap.request.json',
 'fixtures/corpus/key-order.package.json',
 'fixtures/corpus/key-order.request.json',
 'fixtures/corpus/label-qpu.package.json',
 'fixtures/corpus/label-qpu.request.json',
 'fixtures/corpus/label-simulator.package.json',
 'fixtures/corpus/label-simulator.request.json',
 'fixtures/corpus/mapping-corrupt.package.json',
 'fixtures/corpus/mapping-corrupt.request.json',
 'fixtures/corpus/mapping-swap.package.json',
 'fixtures/corpus/mapping-swap.request.json',
 'fixtures/corpus/missing-raw.package.json',
 'fixtures/corpus/missing-raw.request.json',
 'fixtures/corpus/negative-count.package.json',
 'fixtures/corpus/negative-count.request.json',
 'fixtures/corpus/nonfinite.package.json',
 'fixtures/corpus/nonfinite.request.json',
 'fixtures/corpus/out-of-range-bits.package.json',
 'fixtures/corpus/out-of-range-bits.request.json',
 'fixtures/corpus/package-digest.package.json',
 'fixtures/corpus/package-digest.request.json',
 'fixtures/corpus/parameters-swap.package.json',
 'fixtures/corpus/parameters-swap.request.json',
 'fixtures/corpus/path-reference.package.json',
 'fixtures/corpus/path-reference.request.json',
 'fixtures/corpus/postprocessor.package.json',
 'fixtures/corpus/postprocessor.request.json',
 'fixtures/corpus/provider-swap.package.json',
 'fixtures/corpus/provider-swap.request.json',
 'fixtures/corpus/raw-corrupt.package.json',
 'fixtures/corpus/raw-corrupt.request.json',
 'fixtures/corpus/raw-digest.package.json',
 'fixtures/corpus/raw-digest.request.json',
 'fixtures/corpus/request-digest.package.json',
 'fixtures/corpus/request-digest.request.json',
 'fixtures/corpus/request-id-swap.package.json',
 'fixtures/corpus/request-id-swap.request.json',
 'fixtures/corpus/result-corrupt.package.json',
 'fixtures/corpus/result-corrupt.request.json',
 'fixtures/corpus/sample-a.package.json',
 'fixtures/corpus/sample-a.request.json',
 'fixtures/corpus/sample-b.package.json',
 'fixtures/corpus/sample-b.request.json',
 'fixtures/corpus/shot-order.package.json',
 'fixtures/corpus/shot-order.request.json',
 'fixtures/corpus/shots-mismatch.package.json',
 'fixtures/corpus/shots-mismatch.request.json',
 'fixtures/corpus/source-swap.package.json',
 'fixtures/corpus/source-swap.request.json',
 'fixtures/corpus/unverified-provider.package.json',
 'fixtures/corpus/unverified-provider.request.json',
 'fixtures/corpus/weak-projection.package.json',
 'fixtures/corpus/weak-projection.request.json',
 'fixtures/corpus/width-swap.package.json',
 'fixtures/corpus/width-swap.request.json',
 'fixtures/manifest.json',
 'LICENSING.md',
 'profiles/qev-preserved-observation-v0/expected.json',
 'profiles/qev-preserved-observation-v0/mutants.json',
 'profiles/qev-preserved-observation-v0/profile.schema.json',
 'profiles/qev-preserved-observation-v0/rvr-qev.schema.json',
 'profiles/qev-preserved-observation-v0/vectors.json',
 'profiles/qev-preserved-observation-v0/verification-profile.json',
 'pyproject.toml',
 'qev/__init__.py',
 'qev/__main__.py',
 'qev/adapters.py',
 'qev/admission.py',
 'qev/checker.py',
 'qev/corpus.py',
 'qev/inventory.py',
 'qev/mutations.py',
 'qev/rvr_mutations.py',
 'qev/rvr_native.py',
 'qev/semantic_link.mjs',
 'qev/source_inventory.py',
 'qev/source_lock.py',
 'qev/sources.py',
 'README.md',
 'tests/__init__.py',
 'tests/test_admission.py',
 'tests/test_profile.py',
 'tests/test_rvr_native.py',
 'tests/test_standalone.py',
 'tools/__init__.py',
 'tools/build_corpus.py',
 'tools/build_rvr_profile.py',
 'tools/pin_lock.py')
